Class {
	#name : 'TheodoliteMobileLabRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-MobileLab-Theodolite-Namespace',
	#package : 'Rudesheim-MobileLab-Theodolite',
	#tag : 'Namespace'
}

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Application [
	^ ApplicationTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Model [
	^ ModelTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> SpecBuilder [
	^ SpecBuilderTheodoliteMobileLabRudesheim.
]