Class {
	#name : 'TheodoliteMobileLabRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-MobileLab-Theodolite-Namespace',
	#package : 'Rudesheim-MobileLab-Theodolite',
	#tag : 'Namespace'
}

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Application [
	^ ApplicationTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> BearingLines [
	^ BearingLinesTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Key [
	^ KeyTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> LaunchRequested [
	^ LaunchRequestedTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Layer [
	^ LayerTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Markers [
	^ MarkersTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Model [
	^ ModelTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Rays [
	^ RaysTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Renderer [
	^ RendererTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> SpecBuilder [
	^ SpecBuilderTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> ViewLandscape [
	^ ViewLandscapeTheodoliteMobileLabRudesheim.
]

{ #category : 'accessing' }
TheodoliteMobileLabRudesheim class >> Widgets [
	^ WidgetsTheodoliteMobileLabRudesheim.
]
