Class {
	#name : 'MobileLabRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-MobileLab-Namespace',
	#classTraits : 'TApplicationDiscoveryMobileLabRudesheim classTrait',
	#package : 'Rudesheim-MobileLab',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
MobileLabRudesheim class >> Location [
	^ LocationMobileLabRudesheim.
]

{ #category : 'namespace' }
MobileLabRudesheim class >> ScreenPolicy [
	^ ScreenPolicyMobileLabRudesheim.
]

{ #category : 'namespace' }
MobileLabRudesheim class >> WorldMenu [
	^ WorldMenuMobileLabRudesheim.
]
