Extension { #name : 'ExportMobileLabRudesheim' }

{ #category : '*Rudesheim-MobileLab-Tests' }
ExportMobileLabRudesheim class >> StubApp [
	^ StubAppExportMobileLabRudesheim.
]

{ #category : '*Rudesheim-MobileLab-Tests' }
ExportMobileLabRudesheim class >> StubApplication [
	^ StubApplicationExportMobileLabRudesheim.
]

{ #category : '*Rudesheim-MobileLab-Tests' }
ExportMobileLabRudesheim class >> StubBareApp [
	^ StubBareAppExportMobileLabRudesheim.
]

{ #category : '*Rudesheim-MobileLab-Tests' }
ExportMobileLabRudesheim class >> StubPermission [
	^ StubPermissionExportMobileLabRudesheim.
]
